[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[dev]
  command = "npm run dev"
  port = 3000
  publish = ".next"
  targetPort = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
